Name = "stagnet1"
Level = "INFO"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API.GRPC]
  Hosts = [
    "n01.s.vega.xyz:3002",
    "n02.s.vega.xyz:3002",
    "n03.s.vega.xyz:3002",
    "n04.s.vega.xyz:3002",
    "n05.s.vega.xyz:3002"
  ]
  Retries = 5

[API.REST]
  Hosts = [
    "https://n01.s.vega.xyz",
    "https://n02.s.vega.xyz",
    "https://n03.s.vega.xyz",
    "https://n04.s.vega.xyz",
    "https://n05.s.vega.xyz"
  ]

[API.GraphQL]
  Hosts = [
    "https://n03.s.vega.xyz/query",
  ]

[Console]
  URL = "staging.vega.trading"
  LocalPort = 1847

[TokenDApp]
  URL = "staging.token.vega.xyz"
  LocalPort = 1848
