proxy_app = "tcp://127.0.0.1:26658"
moniker = "node0_n01_s_vega_xyz"
fast_sync = true
db_backend = "goleveldb"
db_dir = "data"
log_level = "main:info,state:info,*:error"
log_format = "plain"
genesis_file = "config/genesis.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_state_file = "data/priv_validator_state.json"
priv_validator_laddr = ""
node_key_file = "config/node_key.json"
abci = "socket"
prof_laddr = ""
filter_peers = false

[rpc]
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = []
cors_allowed_methods = [ "HEAD", "GET", "POST",]
cors_allowed_headers = [ "Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time",]
grpc_laddr = ""
grpc_max_open_connections = 900
unsafe = false
max_open_connections = 900
max_subscription_clients = 100
max_subscriptions_per_client = 5
timeout_broadcast_tx_commit = "10s"
max_body_bytes = 1000000
max_header_bytes = 1048576
tls_cert_file = ""
tls_key_file = ""

[p2p]
laddr = "tcp://0.0.0.0:26656"
external_address = "n01.s.vega.xyz:26656"
seeds = ""
persistent_peers = "6a473fa0c9571deb3c494c9ac64d4dda41adde3f@n01.s.vega.xyz:26656,ca6e178a32324e07893049f1090077b520912803@n02.s.vega.xyz:26656,eea179e9eef3d760c7d6cc675d6a374347806e62@n04.s.vega.xyz:26656,5bacf9530c857635aa1ba57421f9674eb247f602@n05.s.vega.xyz:26656,49d9e6ee15e249c21d35ebe46f72f1ac631b0586@n03.s.vega.xyz:26656"
upnp = false
addr_book_file = "config/addrbook.json"
addr_book_strict = true
max_num_inbound_peers = 40
max_num_outbound_peers = 10
unconditional_peer_ids = ""
persistent_peers_max_dial_period = "0s"
flush_throttle_timeout = "100ms"
max_packet_msg_payload_size = 4096
send_rate = 5120000
recv_rate = 5120000
pex = false
seed_mode = false
private_peer_ids = ""
allow_duplicate_ip = false
handshake_timeout = 20000
dial_timeout = 3000

[mempool]
recheck = true
broadcast = true
wal_dir = ""
size = 10000
max_txs_bytes = 1073741824
cache_size = 20000
max_tx_bytes = 1048576

[fastsync]
version = "v0"

[consensus]
wal_file = "data/cs.wal/wal"
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"
skip_timeout_commit = true
create_empty_blocks = true
create_empty_blocks_interval = "0s"
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

[tx_index]
indexer = "kv"
index_keys = ""
index_all_keys = false

[instrumentation]
prometheus = false
prometheus_listen_addr = "127.0.0.1:46660"
max_open_connections = 3
namespace = "tendermint"
