Name = "stagnet3"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API]
  [API.GRPC]
    Hosts = ["n00.stagnet3.vega.xyz:3002", "n01.stagnet3.vega.xyz:3002", "n02.stagnet3.vega.xyz:3002", "n03.stagnet3.vega.xyz:3002", "n04.stagnet3.vega.xyz:3002", "n05.stagnet3.vega.xyz:3002", "n06.stagnet3.vega.xyz:3002", "n07.stagnet3.vega.xyz:3002", "n08.stagnet3.vega.xyz:3002", "n09.stagnet3.vega.xyz:3002"]
    Retries = 5
  [API.REST]
    Hosts = ["api.n00.stagnet3.vega.xyz", "api.n01.stagnet3.vega.xyz", "api.n02.stagnet3.vega.xyz", "api.n03.stagnet3.vega.xyz", "api.n04.stagnet3.vega.xyz", "api.n05.stagnet3.vega.xyz", "api.n06.stagnet3.vega.xyz", "api.n07.stagnet3.vega.xyz", "api.n08.stagnet3.vega.xyz", "api.n09.stagnet3.vega.xyz",]
  [API.GraphQL]
    Hosts = ["api.n00.stagnet3.vega.xyz/graphql", "api.n01.stagnet3.vega.xyz/graphql", "api.n02.stagnet3.vega.xyz/graphql", "api.n03.stagnet3.vega.xyz/graphql", "api.n04.stagnet3.vega.xyz/graphql", "api.n05.stagnet3.vega.xyz/graphql", "api.n06.stagnet3.vega.xyz/graphql", "api.n07.stagnet3.vega.xyz/graphql", "api.n08.stagnet3.vega.xyz/graphql", "api.n09.stagnet3.vega.xyz/graphql",]
