GatewayEnabled = true
[SqlStore]
  WipeOnStartup = true
  Level = "Info"
  UseEmbedded = false
  [SqlStore.ConnectionConfig]
    Port = 5432
    Host = "127.0.0.1"
    Username = "vega"
    Password = "{{- env "POSTGRES_VEGA_PASSWORD" -}}"
    Database = "vega0"
    UseTransactions = true

[API]
  Level = "Info"
  Port = 3007
  CoreNodeGRPCPort = 3002

[Pprof]
  Level = "Info"
  Enabled = true
  Port = 6060
  ProfilesDir = "/local/vega/.data-node"

[Gateway]
  Level = "Info"
  [Gateway.Node]
    Port = 3007
  [Gateway.GraphQL]
    Port = 3008
  [Gateway.REST]
    Port = 3009
	
[Metrics]
  Level = "Info"
  Timeout = "5s"
  Port = 2113
  Enabled = true
[Broker]
  Level = "Info"
  UseEventFile = false
  [Broker.SocketConfig]
    Port = 3005

[DeHistory]
  Enabled = false