log-level = "info"

proxy-app = "tcp://127.0.0.1:26608"
# TODO: consider using moniker = "{ node_domain }", and generate node_domain in higher level.
moniker = "n0{{ add .NodeNumber 1 }}.stagnet3.vega.xyz"
db-backend = "goleveldb"
db-dir = "data"
log-format = "plain"
genesis-file = "config/genesis.json"
priv-validator-key-file = "config/priv_validator_key.json"
priv-validator-state-file = "data/priv_validator_state.json"
priv-validator-laddr = ""
node-key-file = "config/node_key.json"
abci = "socket"
filter-peers = false

[rpc]
  laddr = "tcp://0.0.0.0:26657"
  cors-allowed-origins = ["*"]
  cors-allowed-methods = ["HEAD", "GET", "POST", ]
  cors-allowed-headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]
  grpc-laddr = ""
  grpc-max-open-connections = 900
  unsafe = false
  max-open-connections = 900
  max-subscription-clients = 100
  max-subscriptions-per-client = 5
  timeout-broadcast-tx-commit = "10s"
  max-body-bytes = 1000000
  max-header-bytes = 1048576
  tls-cert-file = ""
  tls-key-file = ""
  pprof-laddr = ":6061"

[p2p]
  laddr = "tcp://0.0.0.0:26656"
  external-address = "n0{{ add .NodeNumber 1 }}.stagnet3.vega.xyz:26656"
  seeds = ""
  upnp = false
  addr-book-file = "config/addrbook.json"
  addr-book-strict = true
  max-num-inbound-peers = 40
  max-num-outbound-peers = 10
  unconditional-peer-ids = ""
  persistent-peers-max-dial-period = "0s"
  flush-throttle-timeout = "100ms"
  max-packet-msg-payload-size = 4096
  send-rate = 5120000
  recv-rate = 5120000
  pex = false
  seed-mode = false
  private-peer-ids = ""
  allow-duplicate-ip = false
  handshake-timeout = "20s"
  dial-timeout = "3s"
  # consider replacing with something like persistent-peers = "{ node-$i-persistent-peers }"
  persistent-peers = "{{- range $i, $peer := .NodePeers -}}
	  {{- if ne $i 0 }},{{end -}}
	  {{- $peer.ID}}@n0{{ add $peer.Index 1 }}.stagnet3.vega.xyz:26656
  {{- end -}}"

[mempool]
  recheck = true
# {{ if eq .NodeSet.Mode "full" }} # ignore syntax
  broadcast = true
# {{ else }} # ignore syntax
  broadcast = false
# {{end }} # ignore syntax
  wal-dir = ""
  size = 10000
  max-txs-bytes = 1073741824
  cache-size = 20000
  keep-invalid-txs-in-cache = false
  max-tx-bytes = 1048576
  max-batch-bytes = 0

[statesync]
  enable = false
  rpc-servers = ""
  trust-height = 0
  trust-hash = ""
  trust-period = "168h0m0s"
  discovery-time = "15s"
  temp-dir = ""
  chunk-request-timeout = "10s"
  chunk-fetchers = "4"

[blocksync]
  enable = true
  version = "v0"

[consensus]
  wal-file = "data/cs.wal/wal"
  timeout-propose = "3s"
  timeout-propose-delta = "500ms"
  timeout-prevote = "1s"
  timeout-prevote-delta = "500ms"
  timeout-precommit = "1s"
  timeout-precommit-delta = "500ms"
  timeout-commit = "1s"
  double-sign-check-height = 0
  skip-timeout-commit = true
  create-empty-blocks = true
  create-empty-blocks-interval = "0s"
  peer-gossip-sleep-duration = "100ms"
  peer-query-maj23-sleep-duration = "2s"

[tx-index]
  indexer = "kv"

[instrumentation]
  prometheus = true
  prometheus-listen-addr = ":26661"
  max-open-connections = 3
  namespace = "tendermint"
