log_level = "info"

proxy_app = "tcp://127.0.0.1:26608"
# TODO: consider using moniker = "{ node_domain }", and generate node_domain in higher level.
moniker = "n0{{ add .NodeNumber 1 }}.stagnet3.vega.xyz"

[rpc]
  laddr = "tcp://0.0.0.0:26657"
  unsafe = true
  cors_allowed_origins = ["*"]
  cors-allowed-methods = ["HEAD", "GET", "POST", ]
  cors-allowed-headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

[p2p]
  laddr = "tcp://0.0.0.0:26656"
  external_address = "n0{{ add .NodeNumber 1 }}.stagnet3.vega.xyz:26656"
  addr_book_strict = false
  max_packet_msg_payload_size = 4096
  pex = false
  allow_duplicate_ip = true

  # TODO: consider replacing with something like persistent_peers = "{ node_$i_persistent_peers }"
  persistent_peers = "{{- range $i, $peer := .NodePeers -}}
	  {{- if ne $i 0 }},{{end -}}
	  {{- $peer.ID}}@n0{{ add $peer.Index 1 }}.stagnet3.vega.xyz:26656
  {{- end -}}"

[mempool]
  size = 10000
  cache_size = 20000

[consensus]
  skip_timeout_commit = false