[Admin.Server]
  SocketPath = "/local/vega/vega.sock"
  Enabled = true

[API]
  Port = 3002
  IP = "0.0.0.0"
  [API.REST]
    Port = 3003

[Blockchain]
	[Blockchain.Tendermint]
		ClientAddr = "tcp://127.0.0.1:26657"
		ServerAddr = "0.0.0.0"
		ServerPort = 26608
	[Blockchain.Null]
		Port = 3101

[EvtForward]
	Level = "Info"
	RetryRate = "1s"

[NodeWallet]
	[NodeWallet.ETH]
		Address = "https://ropsten.infura.io/v3/ffa591112b994ab29a076518f14768e1"

[Processor]
	[Processor.Ratelimit]
		Requests = 10000
		PerNBlocks = 1

[Broker]
  [Broker.Socket]
    Port = 3005
    Enabled = true

[Metrics]
  Level = "Info"
  Timeout = "5s"
  Port = 2112
  Path = "/metrics"
  Enabled = true