# FILE IS AUTOMATICALLY MANAGED BY github.com/vegaprotocol/terraform//github
name: "Automated network configuration update for k8s"
"on":
  # support both vega/networks & vega/networks-internal
  push:
    branches:
      - main # networks-internal
      - master # networks
    paths:
      - fairground/fairground.toml # networks
      - stagnet1/stagnet1.toml # networks-internal
      - stagnet2/stagnet2.toml # networks-internal
      - devnet/devnet.toml # networks-internal
      - .github/workflows/push_network_config.yml
jobs:
  update-manifest-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VEGA_CI_SSH_KEY }}
      - run: |
          git config --global user.name 'vega-ci-bot'
          git config --global user.email 'dev@vega.xyz'
          git clone git@github.com:vegaprotocol/k8s.git

          if [ -f fairground/fairground.toml ]; then
            echo "Updating fairground"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks\n|" fairground/fairground.toml
            sed -i 's|^Host.*|Host = "0.0.0.0"|' fairground/fairground.toml
            sed -i 's|^Port.*|Port = 80|' fairground/fairground.toml
            cp fairground/fairground.toml k8s/charts/apps/vegawallet/testnet/files/testnet.toml
            cat k8s/charts/apps/vegawallet/testnet/testnet.toml
          fi

          if [ -f stagnet1/stagnet1.toml ]; then
            echo "Updating stagnet1"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks-internal\n|" stagnet1/stagnet1.toml
            sed -i 's|^Host.*|Host = "0.0.0.0"|' stagnet1/stagnet1.toml
            sed -i 's|^Port.*|Port = 80|' stagnet1/stagnet1.toml
            sed -i 's|^Name.*|Name = "stagnet"|' stagnet1/stagnet1.toml
            cp stagnet1/stagnet1.toml k8s/charts/apps/vegawallet/stagnet/files/stagnet.toml
            cat k8s/charts/apps/vegawallet/stagnet/stagnet.toml
          fi

          if [ -f stagnet2/stagnet2.toml ]; then
            echo "Updating stagnet2"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks-internal\n|" stagnet2/stagnet2.toml
            sed -i 's|^Host.*|Host = "0.0.0.0"|' stagnet2/stagnet2.toml
            sed -i 's|^Port.*|Port = 80|' stagnet2/stagnet2.toml
            cp stagnet2/stagnet2.toml k8s/charts/apps/vegawallet/stagnet2/files/stagnet2.toml
            cat k8s/charts/apps/vegawallet/stagnet2/stagnet2.toml
          fi

          if [ -f devnet/devnet.toml ]; then
            echo "Updating devnet"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks-internal\n|" devnet/devnet.toml
            sed -i 's|^Host.*|Host = "0.0.0.0"|' devnet/devnet.toml
            sed -i 's|^Port.*|Port = 80|' devnet/devnet.toml
            cp devnet/devnet.toml k8s/charts/apps/vegawallet/devnet/files/devnet.toml
            cat k8s/charts/apps/vegawallet/devnet/devnet.toml
          fi

          cd k8s
          if ! git diff --exit-code; then
            git add -A
            git commit -m "Automated network configuration update from repository: $GITHUB_REPOSITORY"
            git pull --rebase
            git push
          fi
